### ISSUE TITLE
OSLC validation does not seem to be valid

### ISSUE THREAD

**Issue by jadelkhoury** [eclipse/lyo.validation#11]
I tested with a simple OSLC resource, where I created an instance that does not set properties whose @oslcoccurs is meant to be exaclyOne. Yet, the validation succeeded.

To reproduce, run the validateOslcResourceWithOslcAnnotations() method in the 
src/test/java/org/eclipse/lyo/validation/ValidationExample.java class. 
(currently, under reviewing https://github.com/eclipse/lyo-validation/pull/10)

**Comment by jadelkhoury** [comment]
@berezovskyi please assign to yash?

**Comment by berezovskyi** [comment]
shall we close it?

**Comment by jadelkhoury** [comment]
if we know it works, why not. I have not tested it, but trust that yash fixed it.
